# Generated by Django 5.0.1 on 2024-02-01 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True, verbose_name='Время последеней попытки')),
                ('status', models.CharField(choices=[('error', 'ошибка'), ('success', 'успешно')], default='success', max_length=10, verbose_name='Статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог сервиса рассылок',
                'verbose_name_plural': 'Логи сервиса рассылок',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['-time'], name='logging_ser_time_bb7689_idx')],
            },
        ),
    ]
