# Generated by Django 5.0.1 on 2024-02-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
